### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by aileen-fisher** [LANL-Seismoacoustics/particleman#5]
Hi Jonathan, I installed the dev environment (excuse the name; I added obspy, jupyter, scipy to another environment particleman-dev), ran pytest, and came up with an error: 

```bash
 (particleman-devorig) bash-4.2$ cd test
(particleman-devorig) bash-4.2$ ls
conftest.py  __pycache__  test_core.py	test_filter.py
(particleman-devorig) bash-4.2$ pytest
ImportError while loading conftest '/data/studies/PyGS/git/particleman/test/conftest.py'.
conftest.py:3: in <module>
    from particleman import stransform
../src/particleman/__init__.py:5: in <module>
    from .core import stransform, istransform
../src/particleman/core.py:6: in <module>
    from .st import st, ist
../src/particleman/st.py:12: in <module>
    libst = ctypes.CDLL(os.path.dirname(__file__) + '/libst' + ext)
E   TypeError: can only concatenate str (not "NoneType") to str
```

(JKM ninja edit: code formatting)

**Comment by jkmacc-LANL** [comment]
Thanks, @aileen-fisher !  This may be due to something like what @byoung4 [found in our `e1` library](https://github.com/LANL-Seismoacoustics/e1/pull/3#issuecomment-858879420).  Python changed the behavior of how to load compiled shared objects.  I'll try to push a quick fix for you, following his change!

**Comment by jkmacc-LANL** [comment]
I've fixed this in `master`, and (most of) the tests pass.  If you've been installing Particleman from source, I think you should be good to go.  If I need to get it to PyPI or if there are any other issues, let me know.  Thanks!

**Comment by aileen-fisher** [comment]
Thanks!  I've rerun pytest and there is one error left; let me know if I should just ignore.




(particleman-dev) bash-4.2$ pytest
============================================================ test session starts =============================================================
platform linux -- Python 3.11.3, pytest-7.3.1, pluggy-1.0.0
rootdir: /data/studies/PyGS/git/particleman
plugins: anyio-3.5.0
collected 11 items                                                                                                                           

test_core.py ..                                                                                                                        [ 18%]
test_filter.py .F......F                                                                                                               [100%]

================================================================== FAILURES ==================================================================
_________________________________________________________ test_instantaneous_azimuth _________________________________________________________

synthetic_data = (60, array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+0...+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00]), 20)

    def test_instantaneous_azimuth(synthetic_data):
        """
        The instantaneous azimuth at 1 Hz should be ~150
        The instantaneous azimuth at 2 Hz should be ~60
        The instantaneous azimuth at 5 Hz should be ~105
        """
        TOL = 1.0 # [degrees]
        POLARIZATION = 'retrograde'
    
        az_retro, n, e, v, fs = synthetic_data
        Sn = stransform(n, Fs=fs, return_time_freq=False)
        Se = stransform(e, Fs=fs)
        Sv = stransform(v, Fs=fs)
    
        xpr = filt.xpr(az_retro)
        with np.errstate(divide='ignore', invalid='ignore'):
            theta = filt.instantaneous_azimuth(Sv, Sn, Se, POLARIZATION, xpr)
    
        assert theta[idx_5hz, idx_10sec] == pytest.approx(az_retro + 45, abs=TOL) # 60 (y axis retrograde wave) + 45 (x-y linear wave)
        assert theta[idx_2hz, idx_10sec] == pytest.approx(az_retro, abs=TOL)
        assert theta[idx_1hz, idx_10sec] == pytest.approx(az_retro + 90, abs=TOL) # 60 (retrograde wave) + 90
>       assert theta[idx_7_5hz, idx_2sec] == pytest.approx(az_retro + 90, abs=TOL) # 60 (retrograde wave) + 90
E       assert 85.40450210437142 == 150 � 1.0e+00
E         comparison failed
E         Obtained: 85.40450210437142
E         Expected: 150 � 1.0e+00

test_filter.py:41: AssertionError
________________________________________________________ test_scalar_azimuth_prograde ________________________________________________________

synthetic_data = (60, array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+0...+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00]), 20)

    def test_scalar_azimuth_prograde(synthetic_data):
        TOL = 1.0 # [degrees]
        POLARIZATION = 'prograde'
    
        az_retro, n, e, v, fs = synthetic_data
        Sn = stransform(n, Fs=fs, return_time_freq=False)
        Se = stransform(e, Fs=fs)
        Sv = stransform(v, Fs=fs)
        xpr = filt.xpr(az_retro)
        with np.errstate(divide='ignore', invalid='ignore'):
            theta = filt.instantaneous_azimuth(Sv, Sn, Se, POLARIZATION, xpr)
        Sr, St = filt.rotate_NE_RT(Sn, Se, theta)
        NIP = filt.NIP(Sr, Sv, polarization=POLARIZATION, eps=0.04)
    
        f = filt.get_filter(NIP, POLARIZATION, threshold=0.8, width=0.1)
        Svhat = filt.shift_phase(Sv, POLARIZATION)
    
        ef = istransform(Se * f, Fs=fs)
        nf = istransform(Sn * f, Fs=fs)
        vfhat = istransform(Svhat * f, Fs=fs)
    
        az = filt.scalar_azimuth(ef, nf, vfhat)
    
>       assert az == pytest.approx(az_retro + 90, abs=TOL)
E       assert 329.9997087423516 == 150 � 1.0e+00
E         comparison failed
E         Obtained: 329.9997087423516
E         Expected: 150 � 1.0e+00

test_filter.py:219: AssertionError
============================================================== warnings summary ==============================================================
../src/particleman/filter.py:321
  /data/studies/PyGS/git/particleman/src/particleman/filter.py:321: DeprecationWarning: invalid escape sequence '\D'
    """

../src/particleman/filter.py:56
  /data/studies/PyGS/git/particleman/src/particleman/filter.py:56: SyntaxWarning: "is" with a literal. Did you mean "=="?
    if polarization is 'retrograde':

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================================== short test summary info ===========================================================
FAILED test_filter.py::test_instantaneous_azimuth - assert 85.40450210437142 == 150 � 1.0e+00
FAILED test_filter.py::test_scalar_azimuth_prograde - assert 329.9997087423516 == 150 � 1.0e+00
=================(particleman-dev) bash-4.2$ pytest
============================================================ test session starts =============================================================
platform linux -- Python 3.11.3, pytest-7.3.1, pluggy-1.0.0
rootdir: /data/studies/PyGS/git/particleman
plugins: anyio-3.5.0
collected 11 items                                                                                                                           

test_core.py ..                                                                                                                        [ 18%]
test_filter.py .F......F                                                                                                               [100%]

================================================================== FAILURES ==================================================================
_________________________________________________________ test_instantaneous_azimuth _________________________________________________________

synthetic_data = (60, array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+0...+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00]), 20)

    def test_instantaneous_azimuth(synthetic_data):
        """
        The instantaneous azimuth at 1 Hz should be ~150
        The instantaneous azimuth at 2 Hz should be ~60
        The instantaneous azimuth at 5 Hz should be ~105
        """
        TOL = 1.0 # [degrees]
        POLARIZATION = 'retrograde'
    
        az_retro, n, e, v, fs = synthetic_data
        Sn = stransform(n, Fs=fs, return_time_freq=False)
        Se = stransform(e, Fs=fs)
        Sv = stransform(v, Fs=fs)
    
        xpr = filt.xpr(az_retro)
        with np.errstate(divide='ignore', invalid='ignore'):
            theta = filt.instantaneous_azimuth(Sv, Sn, Se, POLARIZATION, xpr)
    
        assert theta[idx_5hz, idx_10sec] == pytest.approx(az_retro + 45, abs=TOL) # 60 (y axis retrograde wave) + 45 (x-y linear wave)
        assert theta[idx_2hz, idx_10sec] == pytest.approx(az_retro, abs=TOL)
        assert theta[idx_1hz, idx_10sec] == pytest.approx(az_retro + 90, abs=TOL) # 60 (retrograde wave) + 90
>       assert theta[idx_7_5hz, idx_2sec] == pytest.approx(az_retro + 90, abs=TOL) # 60 (retrograde wave) + 90
E       assert 85.40450210437142 == 150 � 1.0e+00
E         comparison failed
E         Obtained: 85.40450210437142
E         Expected: 150 � 1.0e+00

test_filter.py:41: AssertionError
________________________________________________________ test_scalar_azimuth_prograde ________________________________________________________

synthetic_data = (60, array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+0...+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00]), 20)

    def test_scalar_azimuth_prograde(synthetic_data):
        TOL = 1.0 # [degrees]
        POLARIZATION = 'prograde'
    
        az_retro, n, e, v, fs = synthetic_data
        Sn = stransform(n, Fs=fs, return_time_freq=False)
        Se = stransform(e, Fs=fs)
        Sv = stransform(v, Fs=fs)
        xpr = filt.xpr(az_retro)
        with np.errstate(divide='ignore', invalid='ignore'):
            theta = filt.instantaneous_azimuth(Sv, Sn, Se, POLARIZATION, xpr)
        Sr, St = filt.rotate_NE_RT(Sn, Se, theta)
        NIP = filt.NIP(Sr, Sv, polarization=POLARIZATION, eps=0.04)
    
        f = filt.get_filter(NIP, POLARIZATION, threshold=0.8, width=0.1)
        Svhat = filt.shift_phase(Sv, POLARIZATION)
    
        ef = istransform(Se * f, Fs=fs)
        nf = istransform(Sn * f, Fs=fs)
        vfhat = istransform(Svhat * f, Fs=fs)
    
        az = filt.scalar_azimuth(ef, nf, vfhat)
    
>       assert az == pytest.approx(az_retro + 90, abs=TOL)
E       assert 329.9997087423516 == 150 � 1.0e+00
E         comparison failed
E         Obtained: 329.9997087423516
E         Expected: 150 � 1.0e+00

test_filter.py:219: AssertionError
============================================================== warnings summary ==============================================================
../src/particleman/filter.py:321
  /data/studies/PyGS/git/particleman/src/particleman/filter.py:321: DeprecationWarning: invalid escape sequence '\D'
    """

../src/particleman/filter.py:56
  /data/studies/PyGS/git/particleman/src/particleman/filter.py:56: SyntaxWarning: "is" with a literal. Did you mean "=="?
    if polarization is 'retrograde':

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================================== short test summary info ===========================================================
FAILED test_filter.py::test_instantaneous_azimuth - assert 85.40450210437142 == 150 � 1.0e+00
FAILED test_filter.py::test_scalar_azimuth_prograde - assert 329.9997087423516 == 150 � 1.0e+00
================================================== 2 failed, 9 passed, 2 warnings in 1.02s ===================================================
(particleman-dev) bash-4.2$ 
================================= 2 failed, 9 passed, 2 warnings in 1.02s ===================================================
(particleman-dev) bash-4.2$

**Comment by jkmacc-LANL** [comment]
These are expected fails, unfortunately.  There's an Issue related to it somewhere.  I can mark them as expected to fail in pytest so that it doesn't cause any confusion.  I'm glad you're running the tests😁!

**Comment by aileen-fisher** [comment]
No problem - I'll update Ileana and let her know Particleman is ready for her to use.  Thank you for working this so quickly!

**Comment by jkmacc-LANL** [comment]
The power of a collaboration platform😉
